name: "ClassifiedPop"
description: "ClassifiedPop and Cuerdas Distantes"

gems:
  - jekyll-paginate
  - jemoji

paginate: 30
baseurl: "/dev/classifiedpop"
url: "http://localhost:4000/dev/classifiedpop"
markdown: kramdown
highlighter: rouge
permalink: pretty

# Outputting
paginate_path: /page:num
